.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PW" "1" "February 2016" "" ""
.
.SH "NAME"
\fBpw\fR \- simple password manager
.
.SH "SYNOPSIS"
\fBpw\fR [\-a \fIARCHIVE\fR] [\fICOMMAND\fR] [\fIARGS\fR\.\.\.] [\fIOPTIONS\fR\.\.\.]
.
.SH "DESCRIPTION"
\fBpw\fR is a simple password manager that keeps passwords inside a gpg2(1) encrypted \fItgz\fR archive\. The content of the archive is a directory tree with a file for each password entry\. The first line of the file is the password, and the rest can optionally be additional or related info\. The \fBpw\fR utility provides commands for manipulating the passwords, allowing the user to add, remove, edit, generate passwords etc\.
.
.SH "COMMANDS"
.
.IP "\(bu" 4
\fBls\fR [\fIpath\fR] [\fB\-t\fR,\fB\-\-tree\fR]
.
.IP
List password files, optionally as a tree\.
.
.IP "\(bu" 4
[\fBget\fR] \fIpwfile\fR
.
.IP
Copy to clipboard the password (it will be cleared in seconds)\.
.
.IP "\(bu" 4
\fBshow\fR \fIpwfile\fR
.
.IP
Print out the password contained in the given file\.
.
.IP "\(bu" 4
\fBgen\fR \fIpwfile\fR [\fIlength\fR] [\fB\-n\fR,\fB\-\-no\-symbols\fR] [\fB\-i\fR,\fB\-\-in\-place\fR | \fB\-f\fR,\fB\-\-force\fR]
.
.IP
Generate a new password with optionally no symbols\. Put it on the clipboard and clear board after seconds\. Prompt before overwriting existing password unless forced\. Optionally replace only the first line of an existing file with a new password\.
.
.IP "\(bu" 4
\fBset\fR \fIpwfile\fR [\fB\-e\fR,\fB\-\-echo\fR | \fB\-m\fR,\fB\-\-multiline\fR] [\fB\-f\fR,\fB\-\-force\fR]
.
.IP
Insert new password\. Optionally, echo the password back to the console during entry\. Or, optionally, the entry may be multiline\. Prompt before overwriting existing password unless forced\.
.
.IP "\(bu" 4
\fBedit\fR \fIpwfile\fR
.
.IP
Edit or add a password file using vi\.
.
.IP "\(bu" 4
\fBfind\fR \fIpattern\fR [\fB\-t\fR,\fB\-\-tree\fR]
.
.IP
List pwfiles that match pattern, optionally in tree format\.
.
.IP "\(bu" 4
\fBgrep\fR \fIsearch\-string\fR
.
.IP
Search for password files containing search\-string when decrypted\.
.
.IP "\(bu" 4
\fBrm\fR \fIpwfile\fR [\fB\-r\fR,\fB\-\-recursive\fR] [\fB\-f\fR,\fB\-\-force\fR]
.
.IP
Remove existing password file or directory, optionally forcefully\.
.
.IP "\(bu" 4
\fBmv\fR \fIold\-path\fR \fInew\-path\fR [\fB\-f\fR,\fB\-\-force\fR]
.
.IP
Renames or moves old\-path to new\-path, optionally forcefully\.
.
.IP "\(bu" 4
\fBcp\fR \fIold\-path\fR \fInew\-path\fR [\fB\-f\fR,\fB\-\-force\fR]
.
.IP
Copies \fIold\-path\fR to \fInew\-path\fR, optionally forcefully\.
.
.IP "\(bu" 4
\fBlog\fR [\-10]
.
.IP
List the history of (last 10) changes\.
.
.IP "\(bu" 4
\fBpass\fR,\fBset\-passphrase\fR
.
.IP
Set the passphrase of the archive (gpg symmetric encryption)\.
.
.IP "\(bu" 4
\fBkeys\fR,\fBset\-keys\fR [\fIgpg\-key\fR\.\.\.]
.
.IP
Set the gpg key(s) of the archive (asymmetric encryption)\.
.
.IP
\fBNote:\fR Symmetric and asymmetric encryption are exclusive; either you use a passphrase (for symmetric encryption), or gpg key(s) (for asymmetric encryption)\.
.
.IP "\(bu" 4
\fBexport\fR \fIdirpath\fR
.
.IP
Export the content of the archive to the given directory\.
.
.IP "\(bu" 4
\fBimport\fR \fIdirpath\fR
.
.IP
Import the content of the archive from the given directory\.
.
.IP "\(bu" 4
\fBhelp\fR
.
.IP
Show this help text\.
.
.IP "\(bu" 4
\fBversion\fR
.
.IP
Show version information\.
.
.IP "" 0
.
.SH "FILES"
\fB~/\.pw/\fR
.
.IP "" 4
.
.nf

      The default `pw` directory\.
.
.fi
.
.IP "" 0
.
.P
\fB~/\.pw/pw\.tgz\.gpg\fR
.
.IP "" 4
.
.nf

      The default archive\.
.
.fi
.
.IP "" 0
.
.P
\fB~/\.pw/config\.sh\fR
.
.IP "" 4
.
.nf

      The configuration file\.
.
.fi
.
.IP "" 0
.
.SH "ENVIRONMENT VARIABLES"
\fBPW_DIR\fR
.
.IP "" 4
.
.nf

      Overrides the default `pw` directory\.
.
.fi
.
.IP "" 0
.
.P
\fBEDITOR\fR
.
.IP "" 4
.
.nf

      The location of the text editor used by edit\.
.
.fi
.
.IP "" 0
.
.SH "SIMPLE EXAMPLE"
Some basic usage is demonstrated on the examples below\.
.
.P
user@MacBookPro:~/test$ \fBpw\fR
.
.IP "" 4
.
.nf

Creating a new archive \'/home/user/\.pw/pw\.tgz\'\.
Enter new passphrase for archive \'/home/user/\.pw/pw\.tgz\':
Retype the passphrase for archive \'/home/user/\.pw/pw\.tgz\':
Commands:
    gen, set, ls, get, show, edit, find, grep, rm, mv, cp, log, help
Type q to quit, p to change the passphrase\.
pw>
.
.fi
.
.IP "" 0
.
.P
pw> \fBset test1\fR
.
.IP "" 4
.
.nf

Enter password for test1:
Retype password for test1:
.
.fi
.
.IP "" 0
.
.P
pw> \fBget test1\fR
.
.IP "" 4
.
.nf

Password of test1 sent to clipboard\. Will clear in 45 seconds\.
.
.fi
.
.IP "" 0
.
.P
pw> \fBshow test1\fR
.
.IP "" 4
.
.nf

passw1
.
.fi
.
.IP "" 0
.
.P
pw> \fBtest1\fR
.
.IP "" 4
.
.nf

Password of test1 sent to clipboard\. Will clear in 45 seconds\.
.
.fi
.
.IP "" 0
.
.P
pw> \fBls test1\fR
.
.IP "" 4
.
.nf

passw1
.
.fi
.
.IP "" 0
.
.P
pw> \fBset test2/test3\fR
.
.IP "" 4
.
.nf

Enter password for test2/test3:
Retype password for test2/test3:
.
.fi
.
.IP "" 0
.
.P
pw> \fBgen test2/test4\fR
.
.IP "" 4
.
.nf

Password of test2/test4 sent to clipboard\. Will clear in 45 seconds\.
.
.fi
.
.IP "" 0
.
.P
pw> \fBshow test2/test4\fR
.
.IP "" 4
.
.nf

;oOd~myTkx4_\'wp\.Mw&O\.PmJNSpDoG
.
.fi
.
.IP "" 0
.
.P
pw> \fBls\fR
.
.IP "" 4
.
.nf

test2/test3
test2/test4
test1
.
.fi
.
.IP "" 0
.
.P
pw> \fBls \-t\fR
.
.IP "" 4
.
.nf

├── test1
└── test2
    ├── test3
    └── test4
.
.fi
.
.IP "" 0
.
.P
pw> \fBls test2\fR
.
.IP "" 4
.
.nf

test2/test3
test2/test4
.
.fi
.
.IP "" 0
.
.P
pw> \fBfind test3\fR
.
.IP "" 4
.
.nf

test2/test3
.
.fi
.
.IP "" 0
.
.P
pw> \fBshow test2/test3\fR
.
.IP "" 4
.
.nf

passw3
.
.fi
.
.IP "" 0
.
.P
pw> \fBlog\fR
.
.IP "" 4
.
.nf

2 minutes ago: Add given password for test1\.
2 minutes ago: Add given password for test2/test3\.
2 minutes ago: Add generated password for test2/test4\.
.
.fi
.
.IP "" 0
.
.P
pw> \fBq\fR
.
.P
user@MacBookPro:~/test$
.
.SH "ADVANCED EXAMPLE"
Some more advanced features are shown in the examples below\.
.
.P
user@MacBookPro:~/test$ \fBcp \-a ~/\.pw/ ~/\.passw\fR
.
.P
user@MacBookPro:~/test$ \fBls \-al ~/\.passw\fR
.
.IP "" 4
.
.nf

total 24
drwx\-\-\-\-\-\-  2 user user 4096 Feb 16 22:18 \.
drwxr\-xr\-x 73 user user 4096 Feb 16 22:31 \.\.
\-rw\-\-\-\-\-\-\-  1 user user  250 Feb 16 21:45 config\.sh
\-rw\-\-\-\-\-\-\-  1 user user 8753 Feb 16 22:18 pw\.tgz\.gpg
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBmv ~/\.passw/pw\.tgz\.gpg ~/\.passw/archive1\.tgz\.gpg\fR
.
.P
user@MacBookPro:~/test$ \fBexport PW_DIR=~/\.passw\fR
.
.P
user@MacBookPro:~/test$ \fBecho $PW_DIR\fR
.
.IP "" 4
.
.nf

/home/user/\.passw
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw \-a archive1 ls \-\-tree\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
├── test1
└── test2
    ├── test3
    └── test4
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw \-a archive1 set "test2/test 5" \-\-multiline\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
Enter contents of test2/test 5 and press Ctrl+D when finished:

password
line 2
line 3
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw \-a archive1 show "test2/test 5"\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
password
line 2
line 3
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw \-a archive1 gen "test2/test 5" 40 \-\-no\-symbols \-\-in\-place\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
Password of test2/test 5 sent to clipboard\. Will clear in 45 seconds\.
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw \-a archive1 show "test2/test 5"\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
3jXaVyxixcfnkYRR3xBr70kGxKK0I83LCmaMGeVc
line 2
line 3
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBsed \-i ~/\.passw/config\.sh \-e "/ARCHIVE=/c ARCHIVE=archive1"\fR
.
.P
user@MacBookPro:~/test$ \fBPW_DIR=~/\.passw pw ls test2\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
test2/test3
test2/test4
test2/test 5
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw set\-passphrase\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
Enter new passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
Retype the passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
.
.fi
.
.IP "" 0
.
.P
user@MacBookPro:~/test$ \fBpw set\-keys CF90C77B D774A374 EB7D54A8\fR
.
.IP "" 4
.
.nf

Passphrase for archive \'/home/user/\.passw/archive1\.tgz\':
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
\fBpw\fR was written by Dashamir Hoxha (userhoxha@gmail\.com)\. The code is on GitHub at https://github\.com/dashohoxha/pw\. \fBpw\fR started as a fork of \fBpass\fR ⟨http://www\.passwordstore\.org/⟩, written by Jason A\. Donenfeld ⟨Jason@zx2c4\.com⟩\.
.
.SH "COPYLEFT"
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\.
.
.P
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\. See the GNU General Public License for more details\.
.
.P
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Soft‐ ware Foundation, Inc\., 51 Franklin Street, Fifth Floor, Boston, MA 02110\-1301, USA\.
.
.SH "SEE ALSO"
gpg2(1), pwgen(1), xclip(1)\.
